
spring:
    application:
        name: Hello World!
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:target/example
        user: sa
        password: sa
    jpa:
        hibernate:
            ddl-auto: false
        database: H2
        show-sql: true
    freemarker:
        cache: false
        templateLoaderPath: classpath:/views/  

# admin

management:

    port: 8081

# liquibase
    
liquibase:
    change-log: classpath:/migrations.xml
    drop-first: true
    enabled: false  
